import * as Localization from "expo-localization";
import { initReactI18next } from "react-i18next";
import i18n from "i18next";

const init = () => {
  // Set the key-value pairs for the different languages you want to support.
  i18n.use(initReactI18next).init(
    {
      lng: Localization.locale,
      fallbackLng: ["en", "he"],
      resources: {
        en: {
          translation: {
            login: "Login",
            register: "Register",
            logout: "Log Out",
            feed: "Feed",
            email: "Email",
            account: "My Account",
            myListings: "My Listings",
            myMessages: "My Messages",
            myActivity: "My Activity",
            settings: "Settings",
            password: "Password",
            language: "Language",
            help: "Help",
            about: "About",
            theme: "Theme",
            light: "Light",
            dark: "Dark",
            average_title: "Daily Average",
            average_description:
              "Average time you spent per day using the SellIt app on this device in the last week",
            m: "m",
            h: "h",
            save: "Save",
            new_password: "New password",
            new_password_again: "New password, Again",
            current_password: "Current password",
            Name: "Name",
            Bio: "Bio",
            "E-mail Address": "E-mail Address",
            "Phone Number": "Phone Number",
            forgotPassword: "Forgot Password",
            notification: "Notification",
            account: "My Account",
            gender: "Gender",
            male: "Male",
            female: "Female",
            decline: "Decline To Answer",
            changeP: "Change Profile Photo",
            exitTitle: "Are you sure you to exit?",
            exitSubTitle: "the chnages you made wont be saved",
            cancel: "Cancel",
            ok: "Ok",
            privacyTitle: "Who can see your private details",
            privacyExplain:
              "If you choose not sharing data about 'phone number',you won't be able to sell things(only buy)",
            privacy: "Privacy",
            removePaymentTitle: "Are you sure you want to remove this payment?",
            removePaymentSubtitle: "The payment can't being restored.",
            removeAddressTitle: "Are you sure you want to remove this Address?",
            removePaymentSubtitle: "The Address can't being restored.",
            "Ordered Products": "Ordered Products",
            emptyCartTitle: "Cart Empty",
            emptyCartSubTitle:
              "Go Ahaed, pick some product you like and get back here to complete the buying proccess...",
            "Countinue Shooping": "Countinue Shooping...",
            keyboardPlaceholder: "Type a message...",
            chats: "Chats",
            picture: "Picture",
            today: "today",
            yesterday: "yesterday",
            sendContactTitle: "Add Contact",
            sendContactSubTitle:
              "Do you Want to add this contact to your device?",
            search: "Search",
            add_contact: "Add to contacts",
            background: "Background",
            report: "Report",
          },
        },
        he: {
          translation: {
            login: "התחבר",
            register: "הירשם",
            logout: "התנתק",
            feed: "דף הבית",
            email: 'דוא"ל',
            account: "החשבון שלי",
            myListings: "הרשימה שלי",
            myMessages: "ההודעות שלי",
            myActivity: "הפעילות שלי",
            settings: "הגדרות",
            password: "סיסמא",
            language: "שפה",
            about: "עלינו",
            help: "עזרה",
            theme: "רקע",
            light: "בהיר",
            dark: "כהה",
            average_title: "ממוצע יומי",
            average_description:
              "הזמן הממוצע שבילית באפליקצייה במכשיר זה בשבוע האחרון בכל יום",
            m: "ד",
            h: "ש",
            save: "שמור",
            new_password: "הסיסמא החדשה",
            new_password_again: "הסיסמא החדשה,שוב",
            current_password: "הסיסמא הנוכחית",
            Name: "שם",
            Bio: "תיאור",
            "E-mail Address": 'כתובת דוא"ל',
            "Phone Number": "מספר טלפון",
            forgotPassword: "שכחתי סיסמא",
            notification: "התראות",
            account: "החשבון שלי",
            gender: "מין",
            male: "גבר",
            female: "אישה",
            decline: "מעדיף לא לענות",
            changeP: "שנה תמונת פרופיל",
            exitTitle: "האם את/ה בטוח שאתה רוצה לצאת?",
            exitSubTitle: "השינוים שעשית לא ישמרו",
            cancel: "בטל",
            ok: "אוקיי",
            privacyTitle: "מי יכול/ה לראות את הפרטים האישיים שלך",
            privacyExplain:
              "אם תבחר/י שלא לשתף מידע לגבי 'מספר טלפון',לא תוכל/י למכור דברים",
            privacy: "פרטיות",
            removePaymentTitle:
              "האם את/ה בטוח/ה שאת/ה רוצה למחוק את אמצעי התשלום?",
            removePaymentSubtitle:
              "לא תוכל/י לשחזר את אמצעי התשלום לאחר המחיקה...",
            removeAddressTitle: "האם את/ה בטוח/ה שברצונך למחוק כתובת זו?",
            removePaymentSubtitle: "לא תוכל/י לשחזר את הכתובת",
            "Ordered Products": "מוצרים שהוזמנו",
            emptyCartTitle: "Cart Empty",
            emptyCartSubTitle:
              "Go Ahaed, pick some product you like and get back here to complete the buying proccess...",
            "Countinue Shooping": "המשך בקנייה...",
            keyboardPlaceholder: "הקלד/י הודעה...",
            chats: "צ'אטים",
            picture: "תמונה",
            yesterday: "אתמול",
            today: "היום",
            sendContactTitle: "הוספת איש קשר",
            sendContactSubTitle: "האם אתה רוצה להוסיף את איש קשר זה למכשירך?",
            search: "חיפוש",
            add_contact: "הוסף לאנשי קשר",
            background: "רקע",
            report: "דווח",
          },
        },
      },
    },
    (err, t) => console.log("init done error is:", err)
  );
};
export default { init };
