export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LISTINGS: "Listings",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  ACCOUNT_LISTINGS: "Listings",
  EDIT_PROFILE: "ProfileEdit",
  SETTINGS: "Settings",
  CHANGE_PASSWORD: "Password",
  CHANGE_LANGUAGE: "Language",
  HELP: "Help",
  ABOUT: "About",
  ACTIVITY: "Activity",
  THEME: "Theme",
  LISTING_IMAGE: "ViewListingImage",
  VALIDATE_EMAIL: "Verify",
  FORGOT_PASSWORD: "ForgotPassword",
  MY_CART: "CartDetails",
  CHECKOUT: "Checkout",
  ADD_PAYMENT: "AddPaymentMethod",
  ADD_ADDRESS: "AddAddress",
  OPTIONS_PICKER: "OptionsPicker",
  ORDERED_ITEMS: "Orderd Listings",
  CHATS: "Chats",
});
